swagger: '2.0'
info:
  title: 'Num API'
  version: 1.0.0
  description: 'Numbers, numbers everywhere....'
basePath: '/~polickya/numapi'
host: 'webik.ms.mff.cuni.cz'
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json

paths:
  '/unary/negation':
    get:
      operationId: getUnaryNegation
      description: 'Oposite'
      parameters:
        -
          name: input
          type: number
          format: double
          in: query
          required: true
          description: 'This is the input'
      responses:
        '200':
          $ref: '#/responses/Result'

  '/binary/{op}':
    get:
      operationId: getBinaryOperation
      description: 'Apply operation on two numbers'
      parameters:
        -
          name: op
          type: string
          enum:
            - add
            - sub
          in: path
          required: true
          description: 'Name of the operation'
        -
          name: left
          type: number
          format: double
          in: query
          required: true
          description: 'Left operand'
        -
          name: right
          type: number
          format: double
          in: query
          required: true
          description: 'Right operand'
      responses:
        '200':
          $ref: '#/responses/Result'

responses:
  'Result':
    description: 'Result of arithmetic operation'
    schema:
      type: object
      properties:
        'result':
          type: number
          format: double